### ISSUE TITLE
NPE: getCurrentPosition

### ISSUE THREAD

**Issue by PaulWoitaschek** [AntennaPod/AntennaPod-AudioPlayer#2]
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.media.MediaExtractor.getSampleTime()' on a null object reference
at org.antennapod.audio.SonicAudioPlayer.getCurrentPosition(SonicAudioPlayer.java:125)
at org.antennapod.audio.MediaPlayer.getCurrentPosition(MediaPlayer.java:690)

**Comment by mfietz** [comment]
https://github.com/AntennaPod/AntennaPod/blob/develop/CONTRIBUTING.md#how-to-report-a-bug

**Comment by PaulWoitaschek** [comment]
Sorry for the poor bugreport, I thought it is selfexplaining.

I use the AntennaPod Player in [Material Audiobook Player] and I saw that crash reported by ACRA.
It appeared with the latest version 1.0.7. It appeared on Android 6.0.1 on a Nexus 4.

**Comment by mfietz** [comment]
Still not really sure what happened here.
For ``mExtractor`` to be null, either ``prepare[Async]()`` was not called or it was called in the wrong state. (Maybe after a reset)

**Comment by PaulWoitaschek** [comment]
A detailed report can be found [here](http://acra-63e870.smileupps.com/acralyzer/_design/acralyzer/index.html#/reports-browser/material/bug/ec291aba41f40467c61df4affd39ef49).

According to the [documentation](https://developer.android.com/reference/android/media/MediaPlayer.html) the only invalid state for getCurrentPosition is `ERROR`.

**Comment by mfietz** [comment]
> According to the documentation the only invalid state for getCurrentPosition is ERROR.

Don't understand. Are you reading that from the "Valid and invalid states" table, "Invalid states" column? ;)

This is not a state problem, btw. The MediaExtractor ``getCurrentPosition()`` is called on is null.

**Comment by PaulWoitaschek** [comment]
I am talking about the Android MediaPlayer states as stated in the state diagram.

I suggest to patch the current implementation to

```java
public int getCurrentPosition() {
    switch (mCurrentState) {
        case STATE_ERROR:
        case STATE_IDLE:
            return 0;
        default:
            return (int) (mExtractor.getSampleTime() / 1000);
    }
}
````

The crash can be simply reproduced by

```java
SonicAudioPlayer player = new SonicAudioPlayer();
player.getCurrentPosition;
```

and should be fixed by covering the idle state.
