### ISSUE TITLE
IllegalStateException: play() called on uninitialized AudioTrack

### ISSUE THREAD

**Issue by mfietz** [AntennaPod/AntennaPod-AudioPlayer#8]
Getting an awful lot of 
```
java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
	at android.media.AudioTrack.play(AudioTrack.java:1141)
	at org.antennapod.audio.SonicAudioPlayer$2.run(SonicAudioPlayer.java:733)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by PaulWoitaschek** [comment]
That's [here](https://github.com/AntennaPod/AntennaPod-AudioPlayer/blob/master/library/src/main/java/org/antennapod/audio/SonicAudioPlayer.java#L733) and therefore exactly after the problematic part I mentioned in #7. 

So probably fixing #7 fixes this.

**Comment by mfietz** [comment]
I wonder if this is caused by https://code.google.com/p/android/issues/detail?id=61031

**Comment by mfietz** [comment]
Let's call this a duplicate of #7
